pub const B: usize = 2;
pub const fn build_B2_minus_1_none<T>() -> [Option<T>; 2 * B - 1] {
    [None, None, None]
    //[
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None,
    //]
}
