pub const B: usize = 2;
pub const fn build_B2_none<T>() -> [Option<T>; 2 * B] {
    [None, None, None, None]
    //[
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
    //None,
    //]
}
